### PR TITLE
Nine region mapping

### PR DESCRIPTION
**Pull request by EyeOfMidas**
I'm not entirely sure how to do this, but I trekked across the server and copied in my cache files. Let me know if there's something else I need to do to make this easy.

### CODE REVIEW

**Comment by EyeOfMidas** [comment]
This is not the right way to do this. Sorry. I'll submit a different pull request when I've got the correct files merged.

**Comment by benjajaja** [comment]
Sadly we still don't have a renderer for voxelmap, only for the biome overlay.

**Comment by EyeOfMidas** [comment]
I actually started working on that when I realized this was the wrong way to do it. I'm a little stuck though; where can I find information about the bit encoding/offset in the data files? I see how you got biomes and height, but it looks like I'd have to loop over all the blocks in a vertical section to figure out what the top block is. If you had notes about how the data is organized, it might help me modify the generate script.

**Comment by benjajaja** [comment]
https://github.com/gipsy-king/civcraft-voxelmap/blob/master/generate.py has a comment with some info that Maxopoly and Promofaux figured out by reverse engineering voxelmap. It isn't 100% clear to me either.

I started working on a surface map generator, but it's actually not as straightforward as I thought. First, you have to map blocks to colors. This can be done by taking the vanilla texture pack and using the median (or average, whatever) color of a block. This is fine for regular blocks, but there is a huge amount of exceptions and irregularities. Many blocks have special textures for each surface. I've started working on something like that, but was overwhelmed from all the special blocks.

Next, when actually rendering these colors, there should be shades for altitude changes and such, which wasn't trivial to me either.

Here is my (poor) attempt: https://github.com/gipsy-king/civcraft-voxelmap/commit/79a62d51bb64e07b76a103fa2ad3f95c1626c33b

**Pull request closed without merging**
